services:
  valantic.pimcoreforms.liform.button.transformer:
    class: Valantic\PimcoreFormsBundle\Form\Transformer\ButtonTransformer
    parent: Limenius\Liform\Transformer\AbstractTransformer
    tags:
      - { name: liform.transformer, form_type: button }

  valantic.pimcoreforms.liform.hidden.transformer:
    class: Valantic\PimcoreFormsBundle\Form\Transformer\StringTransformer
    parent: Limenius\Liform\Transformer\AbstractTransformer
    tags:
      - { name: liform.transformer, form_type: hidden, widget: hidden }
      - { name: liform.transformer, form_type: week, widget: week }

  valantic.pimcoreforms.liform.file.transformer:
    class: Valantic\PimcoreFormsBundle\Form\Transformer\FileTransformer
    parent: Limenius\Liform\Transformer\AbstractTransformer
    tags:
      - { name: liform.transformer, form_type: file, widget: file }

  valantic.pimcoreforms.liform.string.transformer:
    class: Valantic\PimcoreFormsBundle\Form\Transformer\StringTransformer
    parent: Limenius\Liform\Transformer\AbstractTransformer
    tags:
      - { name: liform.transformer, form_type: date, widget: date }

  valantic.pimcoreforms.form.formerrornormalizer:
    class: Valantic\PimcoreFormsBundle\Form\FormErrorNormalizer
    public: true
    tags:
      - { name: serializer.normalizer, priority: -10 }
    arguments:
      [ '@translator' ]
